# Conditioner-Guide Daten: key -> (Marke, Produkt, Kategorien, Einschätzung, Haarzustand, Gut zu wissen, Segment)
D = "Drogerie"
P = {
"c01": ("L'Oréal Paris Elvital","Glycolic Gloss Conditioner","duenn normal","Leichte Spülung mit Fettalkohol und etwas Amodimethicone, dazu Perlglanz","glanzlos","Die Glykolsäure aus dem Namen steht ganz am Ende der Liste. Den Glanz machen Silikon und Perlglanz-Pigmente.",D),
"c14": ("L'Oréal Paris Elvital","Glycolic Gloss Spiegelglanz Conditioner","normal dick","Pflegende Spülung mit Silikon und Glycerin","glanzlos","Reichhaltiger als der kleine Glycolic Gloss Conditioner. Die Glykolsäure steht auch hier ganz am Ende.",D),
"c02": ("L'Oréal Paris Elvital","Collagen Lifter Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Fettalkohol, Glycerin und leichtem Ölersatz","fein, platt","Kollagen selbst ist nicht drin, nur zwei Peptide ganz hinten in der Liste.",D),
"c03": ("Pantene Pro-V","Repair & Care Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","strapaziert","Panthenol und Histidin stehen erst hinter dem Parfum, nur in kleiner Menge.",D),
"c04": ("L'Oréal Paris Elvital","Hydra Hyaluronic Conditioner","normal dick","Pflegende Spülung mit Silikon und Glycerin","trocken, braucht Feuchtigkeit","Das Hyaluron steht erst weit hinten. Feuchtigkeit bringt vor allem das Glycerin.",D),
"c05": ("Herbal Essences","Fiji mit Kokosnussextrakt Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","trocken","Kokos steht nur als Duft und Extrakt in Spuren drin.",D),
"c06": ("Herbal Essences","Blütensanft Rosenduft Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","normal","Fast die gleiche Basis wie die anderen Herbal-Essences-Spülungen, vor allem der Duft ist anders.",D),
"c07": ("L'Oréal Paris Elvital","Dream Length Conditioner","normal dick","Silikonfreie Spülung mit Fettalkohol, leichtem Ölersatz, Sonnenblumen- und Rizinusöl","lang, strapazierte Spitzen","Die Proteine stehen erst hinter dem Parfum. Spliss repariert keine Spülung, sie kann ihm nur vorbeugen.",D),
"c08": ("Bali Curls","Moisturising Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Sheabutter, Kokosöl und Glycerin","lockig, trocken","",D),
"c09": ("Aussie","Bouncy Curls Conditioner","normal dick","Silikonfreie Spülung mit Fettalkoholen","lockig oder wellig","",D),
"c10": ("L'Oréal Paris Elvital","Fiber Booster Conditioner","normal dick","Silikonfreie Spülung mit Fettalkohol, Glycerin, leichtem Ölersatz und Sojaöl","dünner werdend","Das Aminexil steht hinter dem Parfum und wird ausgespült. Gegen Haarverlust kann eine Spülung kaum etwas tun.",D),
"c11": ("Schwarzkopf Gliss","Liquid Silk Conditioner","normal dick","Pflegende Spülung mit Silikon und leichtem Ölersatz, dazu etwas Seidenprotein","glanzlos, spröde","",D),
"c12": ("L'Oréal Paris Elvital","Bond Repair Conditioner","duenn normal","Leichte Spülung mit Fettalkohol und etwas Amodimethicone","strapaziert","„Bond Repair“ steht im Namen. Einen Bond-Wirkstoff in nennenswerter Menge finde ich in der Liste nicht.",D),
"c13": ("Herbal Essences","Repair Arganöl Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","strapaziert","Das Arganöl steht erst hinter dem Parfum, nur in kleiner Menge.",D),
"c15": ("syoss","Intense Keratin Conditioner","normal dick kaputt","Pflegende Spülung mit Fettalkohol, leichtem Ölersatz, Keratin und etwas Silikon","strapaziert, brüchig","",D),
"c16": ("Garnier Wahre Schätze","Sanfte Hafermilch Conditioner","normal dick","Silikonfreie Spülung mit Glycerin, leichtem Ölersatz, Soja- und Sonnenblumenöl","normal, empfindliche Kopfhaut","",D),
"c17": ("Garnier Wahre Schätze","Honig Schätze Conditioner","normal dick","Silikonfreie Spülung mit Fettalkohol und leichtem Ölersatz","strapaziert","Honig und Sonnenblumenöl stehen hinter dem Parfum, nur in kleiner Menge.",D),
"c18": ("Langhaarmädchen","Hydrate & Shine Conditioner","duenn normal","Leichte, silikonfreie Spülung mit viel Glycerin und Panthenol","braucht Feuchtigkeit","",D),
"c19": ("L'Oréal Paris Elvital","Hydra Hyaluronic Pure Conditioner","duenn normal","Leichte Spülung mit viel Glycerin und etwas Silikon","fettiger Ansatz, trockene Längen","",D),
"c20": ("Balea Professional","Oil Repair Intensiv Conditioner","dick sehrdick kaputt","Reichhaltige, silikonfreie Spülung mit Glycerin, Keratin und fünf Ölen","stark strapaziert, trocken","",D),
"c21": ("John Frieda","Frizz Ease Wunder-Reparatur Conditioner","normal dick","Silikonfreie Spülung mit leichtem Ölersatz, Panthenol, Oliven- und Rizinusöl","strapaziert, frizzig","Das Ceramid steht weit hinten.",D),
"c22": ("Herbal Essences","Feuchtigkeit Aloe Vera Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","trocken","Die Aloe steht erst hinter dem Parfum.",D),
"c23": ("Herbal Essences","Limettenduft Tiefenreinigung & Glanz Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Fettalkoholen","fettiger Ansatz","",D),
"c24": ("Jean&Len","Hydration Pfirsich Chia Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Fettalkohol und leichtem Ölersatz","braucht Feuchtigkeit","",D),
"c25": ("Garnier Fructis","Keratin Sleek Conditioner","normal dick kaputt","Pflegende Spülung mit Amodimethicone, Arganöl und Pflanzenproteinen","frizzig, strapaziert","",D),
"c26": ("OGX","Argan Oil of Morocco Conditioner","normal dick","Pflegende Spülung mit Glycerin, Arganöl und Silikon","trocken, strapaziert","",D),
"c27": ("Balea Professional","Aqua Hyaluron Conditioner","duenn normal","Sehr leichte, silikonfreie Spülung mit Fettalkohol und Glycerin","braucht Feuchtigkeit","Das Hyaluron steht erst hinter dem Parfum.",D),
"c28": ("John Frieda","Frizz Ease Traumlocken Conditioner","normal dick","Silikonfreie Spülung mit leichtem Ölersatz, Panthenol und Hagebuttenöl","lockig, frizzig","",D),
"c29": ("Langhaarmädchen","Lovely Long Conditioner","normal dick","Silikonfreie Spülung mit Fettalkoholen, Arganöl und etwas Weizenprotein","lang","",D),
"c30": ("Balea Professional","Plex Care Conditioner","normal dick kaputt","Pflegende Spülung mit Glycerin, Rizinusöl, Erbsenprotein und Aminosäuren","strapaziert, chemisch behandelt","„Plex“ klingt nach Bond-Wirkstoff. Drin sind aber vor allem Proteine und Aminosäuren, die von außen pflegen.",D),
"c31": ("OGX","Biotin & Collagen Conditioner","duenn normal kaputt","Pflegende Spülung mit Glycerin, Kollagen und Silikon","dünn, wenig Fülle","Biotin über die Haare hat keinen Einfluss auf das Wachstum. Das Kollagen steht aber weit vorne und pflegt von außen.",D),
"c32": ("OGX","Bond Protein Repair Conditioner","normal dick","Pflegende Spülung mit Glycerin und Silikon","strapaziert","Bond-Wirkstoff und Weizenprotein stehen hinter dem Parfum, nur in kleiner Menge. Darum nicht bei „Kaputte Haare“.",D),
"c33": ("Balea Professional","Keratin Repair Conditioner","duenn normal kaputt","Silikonfreie Spülung mit Keratin und drei Pflanzenproteinen, ohne Öle","strapaziert, brüchig","",D),
"c34": ("Balea","Feuchtigkeit Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Glycerin, Panthenol und Niacinamid","braucht Feuchtigkeit","",D),
"c35": ("Bali Curls","Bonding Repair Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Sojaöl, Sheabutter und Jojobaöl","lockig, strapaziert","„Bonding“ steht im Namen. Einen Bond-Wirkstoff finde ich nicht, das Moringa-Protein steht hinter dem Parfum.",D),
"c36": ("Santé","Intense Hydration Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Sonnenblumenöl, Aloe und Panthenol","braucht Feuchtigkeit","Alkohol steht an 2. Stelle, das ist bei Naturkosmetik oft so. Er wird ausgespült.",D),
"c37": ("Balea","Locken beauty essentials Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Sheabutter, Macadamiaöl und Panthenol","lockig, trocken","",D),
"c38": ("NEQI","Diamond Glass Conditioner","normal dick","Pflegende Spülung mit Glycerin und Silikon","glanzlos","",D),
"c39": ("John Frieda","Frizz Ease Unendlich Smooth Conditioner","normal dick","Silikonfreie Spülung mit leichtem Ölersatz, Panthenol und Aminosäuren","frizzig","",D),
"c40": ("Balea","Intensivpflege Conditioner","normal dick","Silikonfreie Spülung mit Panthenol, Niacinamid und Mandelöl","trocken","",D),
"c41": ("Pantene Pro-V","Moisture Boost Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","trocken","",D),
"c42": ("Aussie","Oh My Gloss Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","glanzlos","",D),
"c43": ("NEQI","Repair Reveal Conditioner","duenn normal kaputt","Silikonfreie Spülung mit Glycerin, Aminosäuren aus Soja und Weizen und Haferpeptid","strapaziert","",D),
"c44": ("Balea Professional","Hydra Volume Conditioner","duenn","Sehr leichte, silikonfreie Spülung mit Hyaluron, Niacinamid und Panthenol","fein, wenig Volumen","",D),
"c45": ("Santé","Glossy Shine Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Sonnenblumenöl und Panthenol","glanzlos","Alkohol steht an 2. Stelle, das ist bei Naturkosmetik oft so. Er wird ausgespült.",D),
"c46": ("OGX","Coconut Miracle Oil Conditioner","dick sehrdick","Reichhaltige Spülung mit Kokosöl, leichtem Ölersatz und Silikon","trocken, frizzig","",D),
"c47": ("Pomélo+Co","Shine Therapy Conditioner","duenn normal","Silikonfreie Spülung mit Glycerin, Panthenol und Essig","glanzlos","Der Essig macht die Spülung sauer, das glättet die Oberfläche und sorgt für Glanz.",D),
"c48": ("Balea Professional","Glossy Color Conditioner","normal dick","Silikonfreie Spülung mit Glycerin, leichtem Ölersatz und Rizinusöl","gefärbt","",D),
"c49": ("Pantene Pro-V","Miracles Lift & Volume Conditioner","duenn normal","Leichte, silikonfreie Spülung mit Fettalkoholen","fein, platt","",D),
"c50": ("Balea","Molecular Care Conditioner","normal dick","Pflegende Spülung mit Kokosöl, Glycerin und etwas Amodimethicone","strapaziert","Weizenprotein und Haferpeptid stehen hinter dem Parfum, nur in kleiner Menge.",D),
"c51": ("Pantene Pro-V","Glowtox Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und Silikon","glanzlos","",D),
"c52": ("NEQI","Moisture Mystery Conditioner","normal dick","Pflegende Spülung mit Fettalkoholen und etwas Amodimethicone","trocken","",D),
"c53": ("Pomélo+Co","Molecular Repair Conditioner","normal dick kaputt","Pflegende, silikonfreie Spülung mit Glycerin, Weizenprotein, Arginin und Mandelöl","strapaziert","",D),
"c54": ("Garnier Wahre Schätze","Reiswasser Ritual & Stärke Conditioner","normal dick","Silikonfreie Spülung mit Glycerin, leichtem Ölersatz, Soja- und Sonnenblumenöl","lang","Das Reiswasser steht hinter den Ölen.",D),
"c55": ("syoss","Intense Glaze Conditioner","normal dick kaputt","Saure Spülung mit Keratin und leichtem Ölersatz, etwas Silikon","glanzlos, strapaziert","",D),
"c56": ("Schwarzkopf Gliss","Aqua Revive Conditioner","normal dick","Pflegende Spülung mit Silikon, leichtem Ölersatz und Glycerin","trocken","",D),
"c58": ("MONDAY","Moisture Conditioner","normal dick","Pflegende Spülung mit Glycerin, Amodimethicone und Sheabutter","trocken","",D),
"c59": ("Balea Professional","Glow & Shine Conditioner","normal dick","Pflegende Spülung mit Glycerin, Rizinusöl und Glykolsäure","glanzlos","",D),
"c60": ("Balea Professional","Brilliant Blond Conditioner","normal dick","Silikonfreie Spülung mit Glycerin, Jojobaöl, Panthenol und etwas Keratin","blondiert","Das Keratin steht eher weit hinten. Für stark blondierte Haare zusätzlich eine Repair-Maske.",D),
"c61": ("alverde","Ultra Sensitiv Conditioner","duenn normal","Milde, silikonfreie Spülung mit Glycerin, Sonnenblumenöl und Aloe, ohne Parfum","normal, empfindliche Kopfhaut","",D),
"c63": ("Balea Professional","Traumlocken Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Sheabutter, Weizenkeim- und Kamelienöl","lockig","",D),
}
# Repair-Wirkstoffe für „Kaputte Haare“ (alle wirken bei einer Spülung von außen)
AUSSEN = "Wirkt von außen: Die Proteine legen sich an beschädigte Stellen an und machen das Haar widerstandsfähiger. Eine Spülung wirkt nur kurz, für mehr Aufbau zusätzlich eine Repair-Maske."
REP = {
"c15": [AUSSEN, ["Keratin (Hydrolyzed Keratin)"]],
"c20": [AUSSEN, ["Keratin (Hydrolyzed Keratin)"]],
"c25": [AUSSEN, ["Maisprotein (Hydrolyzed Corn Protein)","Sojaprotein (Hydrolyzed Soy Protein)","Weizenprotein (Hydrolyzed Wheat Protein)"]],
"c30": [AUSSEN, ["Erbsenprotein (Hydrolyzed Pea Protein)","Aminosäuren (Arginine, Serine)"]],
"c31": [AUSSEN, ["Kollagen (Hydrolyzed Collagen)"]],
"c33": [AUSSEN, ["Keratin (Hydrolyzed Keratin)","Weizen-, Mais- und Sojaprotein"]],
"c43": [AUSSEN, ["Aminosäuren aus Soja und Weizen","Haferpeptid (Avena Sativa Peptide)"]],
"c53": [AUSSEN, ["Weizenprotein (Hydrolyzed Wheat Protein)","Aminosäure Arginin"]],
"c55": [AUSSEN, ["Keratin (Hydrolyzed Keratin)","saurer pH durch Zitronen- und Bernsteinsäure"]],
}

# Rossmann (Lauras Screenshots)
P.update({
"r01": ("OGX","Brazilian Keratin Smooth Conditioner","dick sehrdick kaputt","Reichhaltige Spülung mit Keratin, Kokos- und Avocadoöl, Kakaobutter und Silikon","frizzig, strapaziert","",D),
"r02": ("Schwarzkopf Gliss","Sealing Miracle Sealing Conditioner","duenn normal kaputt","Leichte, silikonfreie Spülung mit Erbsenpeptid und leichtem Ölersatz","Spliss, strapazierte Spitzen","Spliss lässt sich nicht versiegeln oder reparieren. Die Spülung kann ihn nur kurz kaschieren, weg geht er nur mit der Schere.",D),
"r03": ("ISANA Professional","Plex Spülung","duenn normal kaputt","Silikonfreie Spülung mit Glycerin, Panthenol und Reisprotein","strapaziert","„Plex“ klingt nach Bond-Wirkstoff. Drin sind aber Proteine, die von außen pflegen.",D),
"r04": ("OGX","Keratin Oil Conditioner","normal dick kaputt","Pflegende Spülung mit Keratin, Arganöl, Glycerin und Silikon","brüchig, strapaziert","",D),
"r05": ("Dejan Garz","The Foundation Conditioner Deep Hydration","normal dick","Pflegende Spülung mit Glycerin, zwei Silikonen, Panthenol und drei Ölen","trocken","",D),
"r06": ("ISANA Professional","Spülung Arganöl & Pflege","normal dick","Silikonfreie Spülung mit Argan- und Pflaumenkernöl und Panthenol","strapaziert, widerspenstig","",D),
"r07": ("ISANA","Curltastic Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Sheabutter und Kokosöl","lockig","",D),
"r08": ("NIVEA","Hairmilk Shine Spülung","duenn normal","Leichte, silikonfreie Spülung mit Glycerin und etwas Mandelöl","glanzlos","",D),
"r09": ("being","Bye Bye Frizz Anti-Frizz Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Mandel- und Jojobaöl und Sheabutter","frizzig, wellig oder kraus","",D),
"r10": ("ISANA Professional","Spülung Glycol & Glanz","normal dick","Pflegende Spülung mit Glycerin, Rizinusöl und Glykolsäure","glanzlos","Fast die gleiche Rezeptur wie Balea Professional Glow & Shine.",D),
"r11": ("Garnier Wahre Schätze","Kokosmilch & Macadamia Conditioner","normal dick","Silikonfreie Spülung mit Fettalkohol und leichtem Ölersatz","normal bis trocken","Die Öle stehen hinter dem Parfum, nur in kleiner Menge. Fast die gleiche Basis wie Honig Schätze.",D),
"r12": ("MONDAY","Repair Conditioner","dick sehrdick","Reichhaltige Spülung mit Silikon, Sheabutter, Kokos-, Arganöl und Kakaobutter","strapaziert","Das Keratin steht erst hinter dem Konservierungsstoff, nur in Spuren. Darum nicht bei „Kaputte Haare“.",D),
"r13": ("ISANA Professional","Glycolic Shine Spülung","normal dick","Pflegende Spülung mit Glycerin, Silikon, Sojaöl und Glykolsäure","glanzlos","Die Glykolsäure steht hier vor dem Parfum, also in nennenswerter Menge.",D),
"r14": ("neboa","Repair & Shine Regenerierende Spülung","normal dick kaputt","Silikonfreie Spülung mit Mandelöl, mehreren Pflanzenölen und Erbsenprotein","gefärbt, strapaziert","",D),
"r15": ("MONDAY","Smooth Antifrizz Conditioner","normal dick","Pflegende Spülung mit Glycerin, Amodimethicone und Sheabutter","frizzig","Bei Rossmann ist die gleiche Inhaltsstoffliste hinterlegt wie beim MONDAY Moisture. Ob das stimmt, lässt sich nicht sicher sagen.",D),
})
REP.update({
"r01": [AUSSEN, ["Keratin (Hydrolyzed Keratin)"]],
"r02": [AUSSEN, ["Erbsenpeptid (Pisum Sativum Peptide)"]],
"r03": [AUSSEN, ["Reisprotein (Oryza Sativa Seed Protein)"]],
"r04": [AUSSEN, ["Keratin (Hydrolyzed Keratin)"]],
"r14": [AUSSEN, ["Erbsenprotein (Hydrolyzed Pea Protein)","Pflanzenprotein (Hydrolyzed Vegetable Protein)"]],
})
H = "High-End"
P.update({
"o1": ("OGX","ProGrowth + Peptide Conditioner","duenn normal","Pflegende Spülung mit Fettalkohol, Glycerin und etwas Silikon","dünner werdend","Peptid und Reisprotein stehen hinter dem Parfum, nur in kleiner Menge. Gegen Haarverlust kann eine Spülung kaum etwas tun.",D),
"h1": ("Coco & Eve","Bond Therapy Pro Bond Conditioner","normal dick kaputt","Pflegende Spülung mit Kokos, Arganöl, leichtem Ölersatz und Pflanzenprotein","strapaziert, chemisch behandelt","Die Bond-Wirkstoffe stehen hinter dem Parfum, nur in kleiner Menge. Den Repair-Effekt bringt hier das Pflanzenprotein.",H),
"h2": ("Redken","Extreme Conditioner","normal dick","Pflegende Spülung mit Fettalkohol, Glycerin, leichtem Ölersatz und etwas Silikon","strapaziert","Die Proteine stehen hinter Parfum und Konservierer, nur in Spuren. Darum nicht bei „Kaputte Haare“.",H),
"h3": ("Olaplex","No.5 FINE Bond Maintenance Conditioner","duenn kaputt","Leichte, silikonfreie Spülung mit Bond-Wirkstoff, Glycerin und leichtem Ölersatz","fein, strapaziert, chemisch behandelt","",H),
"h4": ("Olaplex","No.5 CURL Bond Shaper Hydrating Curl Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Olivenöl-Ersatz, Rapsöl, Avocadoöl und Glycerin","lockig, trocken","Anders als beim No.5 FINE finde ich hier keinen Bond-Wirkstoff in der Liste. Sie pflegt Locken, repariert aber nicht.",H),
"h5": ("Living Proof","Full Conditioner","duenn","Sehr leichte, silikonfreie Spülung mit Fettalkohol und leichtem Ölersatz","fein, platt","",H),
"h6": ("Living Proof","Restore Conditioner","normal dick","Silikonfreie Spülung mit Jojoba-Estern, Sonnenblumenwachs und Rizinusöl-Ersatz","strapaziert","Pflegt strapaziertes Haar geschmeidig. Für echten Aufbau zusätzlich eine Repair-Maske.",H),
"h7": ("Living Proof","Perfect hair Day Conditioner","normal dick","Silikonfreie Spülung mit Fettalkoholen, Jojoba-Estern und Sonnenblumenwachs","glanzlos, trocken","",H),
"h8": ("Living Proof","No Frizz Conditioner","normal dick","Silikonfreie Spülung mit Jojoba-Estern, Sonnenblumenwachs und einem Anti-Feuchtigkeits-Wirkstoff","frizzig","",H),
"h9": ("OUAI","Thick Hair Conditioner","dick sehrdick","Reichhaltige Spülung mit mehreren Silikonen, Avocadoöl und Sheabutter","dick, trocken","Das Keratin steht hinter dem Parfum, nur in kleiner Menge. Darum nicht bei „Kaputte Haare“.",H),
})
REP.update({
"h1": [AUSSEN, ["Pflanzenprotein (Hydrolyzed Vegetable Protein PG-Propyl Silanetriol)"]],
"h3": ["Wirkt im Inneren: Der Bond-Wirkstoff stabilisiert das Haar von innen. Eine Spülung wirkt nur kurz, für mehr Aufbau zusätzlich eine Repair-Maske.", ["Bond-Wirkstoff (Bis-Aminopropyl Diglycol Dimaleate)"]],
})
P["r16"] = ("being","Curl Power Locken Conditioner","dick sehrdick","Reichhaltige, silikonfreie Spülung mit Kokos-, Traubenkernöl und Sheabutter","lockig","",D)
# Wonder Water und andere flüssige Conditioner: Laura will sie in „Feines Haar“
P.update({
"w1": ("NEQI","Diamond Glass Mirror Rinse","fein","Flüssige Spülung mit Glycerin, Glykolsäure und etwas Silikon","glanzlos","Haferpeptid und Pflanzenextrakte stehen hinter dem Parfum, nur in kleiner Menge.",D),
"w2": ("Schwarzkopf Gliss","Ultimate Repair Express-Repair-Kur 7 sec","fein","Flüssige, silikonfreie Spülung mit Glycerin und leichtem Ölersatz","strapaziert","Bond-Wirkstoffe und Keratin stehen hinter dem Parfum, nur in kleiner Menge. Darum nicht bei „Kaputte Haare“.",D),
"w3": ("ISANA Professional","Haarfluid Wunder Express","fein kaputt","Flüssige, silikonfreie Spülung mit Glycerin und Weizenprotein","strapaziert","",D),
"w4": ("Kérastase","Chroma Absolu Soin Acide Chroma Gloss","fein","Flüssige Spülung mit leichtem Ölersatz, Milchsäure und etwas Silikon","gefärbt, glanzlos","Laut Flasche 0,7 % Milchsäure. Der saure pH glättet die Oberfläche, das bringt Glanz.",H),
"w5": ("L'Oréal Professionnel","Serie Expert Absolut Repair Molecular Rinse-Off Serum","fein kaputt","Flüssige Spülung mit Glycerin, Aminosäuren und etwas Silikon","stark strapaziert","„Molecular“ und „Peptide Bonder“ klingen nach Bond-Wirkstoff. Drin sind vor allem Aminosäuren und Weizenprotein, die von außen pflegen.",H),
"w6": ("L'Oréal Paris Elvital","Dream Length Wonder Water","fein","Flüssige, silikonfreie Spülung mit leichtem Ölersatz","lang, strapazierte Spitzen","Das Weizenprotein steht hinter dem Parfum, nur in kleiner Menge.",D),
"w7": ("amika","flash instant shine mask","fein","Flüssige Spülung mit Glycerin, Leinsamen, Aminosäuren und etwas Silikon","glanzlos","Die Aminosäuren stehen hinter vielen Pflanzenextrakten, also nur in kleiner Menge. Darum nicht bei „Kaputte Haare“.",H),
})
REP.update({
"w3": [AUSSEN, ["Weizenprotein (Hydroxypropyltrimonium Hydrolyzed Wheat Protein)"]],
"w5": ["Wirkt vor allem von außen: Die Aminosäure Glycin lagert sich an, die kleinen Bausteine dringen auch etwas ins Haar ein. Eine Spülung wirkt nur kurz, für mehr Aufbau zusätzlich eine Repair-Maske.", ["Aminosäure Glycin (Glycine)"]],
})
