# Haaröl-Guide: key -> (Marke, Produkt, Kategorien, Einschätzung, Haarzustand, Gut zu wissen, Segment, trockenes Öl)
# Trockenes Öl = Basis aus verdunstenden Stoffen oder leichtem Ölersatz, kein Dimethicone an 1. Stelle, Dimethiconol höchstens ab Platz 5, kein Wasser.
# Hitzeschutz nur mit Angabe des Herstellers (Gradzahl, wenn genannt). „Fast die gleiche Basis wie …“: vor einer Live-Website Laura fragen, ob das bleibt.
D, H = "Drogerie", "High-End"
SER = "Klassisches Silikon-Serum: glättet, bändigt Frizz und gibt Glanz"
P = {
# ---------- Drogerie (Rossmann, Screenshots) ----------
"o01": ("MONDAY","Repair Argan Haaröl","normal dick sehrdick","Glättendes Silikon-Serum mit Arganöl und Squalan","trocken, frizzig","Fast die gleiche Basis wie das OGX Argan Penetrating Oil.",D,False),
"o02": ("ISANA Professional","Haaröl Arganöl & Pflege","normal dick","Leichtes Öl-Serum mit Silikon, Sonnenblumen- und Arganöl","trocken, strapaziert","",D,False),
"o03": ("Aussie","Curls Öl Lightweight Oil","normal dick sehrdick",SER+", lockige Haare werden weicher","lockig, frizzig","",D,False),
"o07": ("Garnier Wahre Schätze","Schwereloses Haar-Öl Argan & Camelia","duenn normal dick","Leichtes Öl-Serum mit Silikon, Argan- und Kamelienöl","trocken, glanzlos","",D,False),
"o14": ("OGX","Argan Oil of Morocco Weightless Reviving Dry Oil","duenn normal dick","Trockenes Sprühöl mit Silikon, Kokos- und Arganöl","trocken, glanzlos","",D,True),
"o20": ("OGX","Bond Protein Repair 3-in-1 Oil Mist","duenn normal","Leichter Pflegenebel auf Wasserbasis mit Pflanzenölen, Glycerin und Weizenprotein","strapaziert","Eher ein leichtes Pflegespray als ein klassisches Öl. Silikonfrei.",D,False),
"o27": ("Dejan Garz","Violet Hair Oil The Britney","fein duenn normal","Trockenes Öl mit Silikon, Kamelien-, Argan- und Jojobaöl","blond, blondiert, strapaziert","Mit Hitzeschutz bis 230 °C. Hinterlässt keinen violetten Schleier auf hellem Haar.",D,True),
"o28": ("Dejan Garz","Sensitive Hair Oil The Gentle","fein duenn normal","Trockenes Öl mit Silikon, Haferöl und Squalan","strapaziert, empfindlich","Ohne Parfum, gut bei Duftallergie oder empfindlicher Haut.",D,True),
# ---------- Drogerie (dm) ----------
"d01": ("OGX","Coconut Miracle Oil","normal dick sehrdick","Glättendes Silikon-Serum mit Argan- und Kokosöl","trocken, strapaziert","Fast die gleiche Basis wie das OGX Argan Penetrating Oil, dazu Kokosöl.",D,False),
"d02": ("OGX","Moroccan Argan Penetrating Oil","normal dick sehrdick","Glättendes Silikon-Serum mit Arganöl","trocken","Laut OGX mit Hitzeschutz.",D,False),
"d03": ("L'Oréal Paris Elvital","Öl Magique","duenn normal dick","Öl-Serum mit Silikon und Kokosöl, dazu Marula- und Kamelienöl","trocken, glanzlos","Mit Hitzeschutz bis 230 °C.",D,False),
"d04": ("L'Oréal Paris Elvital","Öl Magique Jojoba","normal dick sehrdick","Öl-Serum mit Silikon, Kokosöl und festem Jojobaöl","dick, sehr trocken","Durch das feste Jojobaöl etwas reichhaltiger als das normale Öl Magique.",D,False),
"d05": ("Balea Professional","Haaröl Plex Care","normal dick","Leichtes Öl-Serum mit Silikon, Sonnenblumen- und Maiskeimöl","chemisch behandelt, strapaziert","„Plex“ ist der Name der Pflegeserie: Das Öl hat keine Bond-Funktion, sondern macht das Haar geschmeidig, weich und glänzend. Mit Hitzeschutz. Fast die gleiche Basis wie ISANA Haaröl Arganöl & Pflege.",D,False),
"d06": ("Herbal Essences","Arganöl Elixir Tiefenreparatur","normal dick sehrdick",SER+", mit Arganöl","strapaziert, trocken","„Tiefenreparatur“ meint hier, dass trockenes, strapaziertes Haar sichtbar glatter wirkt. Repair-Wirkstoffe hat das Öl nicht, es macht das Haar geschmeidig, weich und glänzend.",D,False),
"d07": ("Balea Professional","Haaröl Oil Repair Intensiv","normal dick","Leichtes Öl-Serum mit Silikon, Sonnenblumen-, Argan-, Babassu- und Marulaöl","sehr trocken, strapaziert","Mit Hitzeschutz bis 230 °C. Fast die gleiche Basis wie ISANA Haaröl Arganöl & Pflege, mit mehr verschiedenen Ölen.",D,False),
"d08": ("Garnier Fructis","Oil Repair Wunder-Öl","normal dick sehrdick","Reichhaltiges Öl-Serum mit Silikon, Oliven-, Sonnenblumen-, Kokos- und Avocadoöl und Sheabutter","trocken","",D,False),
"d09": ("Schwarzkopf Gliss","Tägliches Öl Elixier","normal dick sehrdick","Glättendes Silikon-Serum mit Sonnenblumen- und Arganöl","sehr strapaziert, trocken","„Repariert“ meint hier, dass trockenes, sprödes Haar sichtbar glatter und geschmeidiger wird. Repair-Wirkstoffe hat das Öl nicht.",D,False),
"d10": ("Balea med","Ultra Sensitive 3in1 Haaröl","dick sehrdick","Reines Pflanzenöl aus Sonnenblumen- und Jojobaöl mit Panthenol und Ceramid","trocken, empfindliche Kopfhaut","Ohne Parfum, gut bei Duftallergie oder empfindlicher Kopfhaut. Laut Balea auch für die Kopfhaut: dort 1 bis 2 Stunden vor dem Waschen einwirken lassen, nicht über Nacht.",D,False),
"d11": ("Pantene Pro-V","Hair Glowtox Öl","duenn normal dick","Leichtes Silikon-Serum, ohne Pflanzenöle","glanzlos","",D,False),
"d12": ("Pantene Pro-V","Coconut Infused Oil","normal dick sehrdick",SER+", dazu Panthenol","trocken, glanzlos","",D,False),
"d13": ("Pantene Pro-V","Keratin Protect Oil Repair & Care","normal dick sehrdick",SER+", dazu Panthenol und Vitamin E","strapaziert","„Keratin“ ist hier der Name der Pflegeserie, Keratin ist nicht drin. Das Öl macht das Haar geschmeidig, weich und glänzend. Fast die gleiche Rezeptur wie die LOVE Edition Repair & Care.",D,False),
"d14": ("Pantene Pro-V","Argan Infused Oil Glatt & Seidig","normal dick sehrdick",SER+", dazu Panthenol und Arganöl","frizzig, trocken","",D,False),
"d15": ("Pantene Pro-V","LOVE Edition Repair & Care Haaröl","normal dick sehrdick",SER+", dazu Panthenol und Vitamin E","strapaziert","Fast die gleiche Rezeptur wie das Keratin Protect Oil, nur mit anderem Duft.",D,False),
"d16": ("Balea Professional","Haaröl Traumlocken","dick sehrdick","Reichhaltiges Pflanzenöl mit Argan-, Kokos-, Babassu-, Jojoba- und Weizenkeimöl","lockig, wellig","",D,False),
"d17": ("NEQI","Haaröl Diamond Glass","fein duenn normal","Trockenes Öl mit leichtem Silikon und Sanddornöl","glanzlos","",D,True),
# ---------- High-End ----------
"o04": ("Goldwell","Dualsenses Just Smooth Taming Oil","normal dick sehrdick","Glättendes Silikon-Serum mit Kukuinussöl","frizzig, widerspenstig","",H,False),
"o05": ("Olaplex","No.7 Bonding Oil","normal dick","Konzentriertes Serum mit Silikon, Bond-Wirkstoff und Pflanzenölen","strapaziert, chemisch behandelt","Enthält den Bond-Wirkstoff von Olaplex weit vorne. In einem Öl ist das ein Plus, für echten Aufbau ist eine Repair-Kur aber wichtiger. Bei feinem Haar nur einen Tropfen nehmen. Mit Hitzeschutz bis 232 °C.",H,False),
"o06": ("OUAI","Hair Oil","normal dick sehrdick","Reichhaltiges Öl-Serum mit Silikon, Mandel- und Jojobaöl, Sheabutter und vielen Pflanzenölen","trocken, frizzig","Mit Hitzeschutz bis 232 °C.",H,False),
"o08": ("Kérastase","Elixir Ultime L'Huile Originale","duenn normal dick","Öl-Serum mit Silikon, Kamelien-, Maiskeim-, Argan- und Marulaöl","trocken, glanzlos","Mit Hitzeschutz bis 230 °C. Ähnliche Basis wie das Elvital Öl Magique, mit mehr verschiedenen Ölen.",H,False),
"o09": ("L'Oréal Professionnel","Serie Expert Absolut Repair Molecular Oil","duenn normal","Leichtes Zwei-Phasen-Öl mit Silikon, Wasser, Glycerin und Aminosäuren","strapaziert, frizzig","Mit Aminosäuren, die L'Oréal „Peptide Bonder“ nennt, in kleiner Menge. Mit Hitzeschutz bis 230 °C. Vor Gebrauch schütteln.",H,False),
"o10": ("L'Oréal Professionnel","Serie Expert Absolut Repair Oil","normal dick sehrdick",SER,"strapaziert","„Repair“ meint hier, dass strapaziertes Haar sichtbar glatter und glänzender wird. Repair-Wirkstoffe hat das Öl nicht.",H,False),
"o11": ("Redken","All Soft Argan-6 Oil","normal dick","Leichtes Silikon-Serum mit Arganöl","trocken, frizzig","",H,False),
"o12": ("Wella Professionals","Oil Reflections Luminous Smoothening Oil","normal dick sehrdick",SER,"glanzlos","",H,False),
"o13": ("Kérastase","Première Huile Gloss Réparatrice","fein duenn normal","Trockenes Öl mit Silikon und leichtem Ölersatz, ohne Pflanzenöle","strapaziert, glanzlos","„Réparatrice“ meint hier, dass glanzloses, strapaziertes Haar sichtbar glatter und glänzender wird. Mit Hitzeschutz bis 230 °C. Fast die gleiche Rezeptur wie die Glaze Drops und Redken naked gloss.",H,True),
"o15": ("Wella Professionals","SP Luxe Oil Reconstructive Elixir","normal dick sehrdick",SER,"strapaziert, glanzlos","„Keratin Protection“ steht drauf, Keratin ist aber nicht drin. Das Öl macht das Haar geschmeidig, weich und glänzend.",H,False),
"o16": ("L'Oréal Professionnel","Serie Expert Metal DX Professional Concentrated Oil","duenn normal","Leichtes Pflegeöl mit Silikon, Wasser und Glycerin","gefärbt, blondiert","Mit Hitzeschutz bis 230 °C.",H,False),
"o17": ("Coco & Eve","Like A Virgin Miracle Hair Elixir","normal dick sehrdick","Silikon-Serum mit Kokosöl und weiteren Pflanzenölen","trocken, lockig","Mit Hitzeschutz bis 220 °C.",H,False),
"o18": ("amika","superfruit star lightweight hair styling oil","fein duenn normal","Sehr leichtes trockenes Öl mit Silikon und Sanddornöl","frizzig, glanzlos","Mit Hitzeschutz bis 230 °C.",H,True),
"o19": ("Olaplex","No.7 Shine Serum Oil Mist","fein duenn normal","Leichter Glanznebel mit Silikon, Bond-Wirkstoff und etwas Pflanzenöl","strapaziert, glanzlos","Mit Hitzeschutz bis 232 °C.",H,True),
"o21": ("Redken","naked gloss lightweight shine oil","fein duenn normal","Trockenes Öl mit Silikon und Aprikosenkernöl","glanzlos","Mit Hitzeschutz bis 230 °C. Fast die gleiche Rezeptur wie Kérastase Première Huile Gloss und Glaze Drops.",H,True),
"o22": ("Living Proof","No Frizz Vanishing Oil","fein duenn normal","Trockenes Öl mit Sanddorn-, Sonnenblumen- und Jojobaöl","frizzig","Silikonfrei: Den glättenden Film übernehmen hier Polymere statt Silikone.",H,True),
"o23": ("Gisou","Honey Infused Hair Oil","normal dick sehrdick","Glättendes Silikon-Serum mit Honig, Mandel-, Kokos- und Arganöl","trocken, glanzlos","Mit Hitzeschutz bis 230 °C.",H,False),
"o24": ("Kérastase","Gloss Absolu Glaze Drops","fein duenn normal","Trockenes Öl mit Silikon und leichtem Ölersatz, ohne Pflanzenöle","glanzlos, frizzig","Fast die gleiche Rezeptur wie Kérastase Première Huile Gloss und Redken naked gloss.",H,True),
"o25": ("Gisou","Honey Gloss Collagen Drops","duenn normal dick","Glanz-Serum mit Silikon, Honig, Kollagen und mehreren Pflanzenölen","glanzlos","",H,False),
"o26": ("Sebastian Professional","Dark Oil","dick sehrdick",SER,"glanzlos, frizzig","",H,False),
}
