# Kopfhaut-Guide: Daten
# Felder: key, Marke, Produkt, Kategorien, Art, Einschätzung, wichtige Inhaltsstoffe, Duft/Alkohol, Gut zu wissen, Segment
D, H = "Drogerie", "High-End"
CATS = [
 ("normal", "Normale Kopfhaut", "Deine Kopfhaut macht keine Probleme, du möchtest sie einfach gut versorgen. Hier stehen Pflegen, die vor allem Feuchtigkeit geben, zum Beispiel mit Glycerin, Panthenol oder Hyaluron."),
 ("trocken", "Trockene Kopfhaut", "Die Kopfhaut spannt, fühlt sich rau an oder hat feine, trockene Schüppchen. Hier stehen Pflegen mit viel Feuchtigkeit, zum Beispiel mit Urea, Panthenol oder Glycerin, ohne viel Alkohol. Dazu Öle für vor der Wäsche."),
 ("sensibel", "Sensible Kopfhaut", "Die Kopfhaut reagiert schnell, wird rot oder brennt. Hier stehen nur milde Pflegen ohne Parfum und ohne viel Alkohol, meist mit beruhigenden Wirkstoffen wie Panthenol, Allantoin oder Bisabolol."),
 ("juckreiz", "Juckende Kopfhaut", "Die Kopfhaut juckt, oft weil sie trocken oder gereizt ist. Hier stehen Pflegen mit beruhigenden Wirkstoffen, zum Beispiel Urea, Polidocanol, Allantoin oder Panthenol. Juckt es trotz Pflege über Wochen, lass es beim Hautarzt anschauen."),
 ("schuppen", "Schuppige Kopfhaut", "Gegen Schuppen, bei denen ein Hefepilz eine Rolle spielt. Wirklich dagegen arbeitet vor allem Piroctone Olamine. Hier stehen Pflegen, die so einen Wirkstoff enthalten. Am besten zusammen mit einem Anti-Schuppen-Shampoo."),
 ("fettend", "Schnell fettende Kopfhaut", "Der Ansatz ist schnell wieder fettig. Hier stehen leichte Pflegen ohne Öle: welche, die den Talg regulieren sollen, zum Beispiel mit Niacinamid oder Zink, und leichte Feuchtigkeitspflegen. Auch eine fettige Kopfhaut kann Feuchtigkeit brauchen."),
 ("peeling", "Kopfhautpeeling", "Ein Peeling ist kein Pflegeprodukt für einen bestimmten Kopfhauttyp, sondern eine Reinigung zwischendurch. Es löst Rückstände, Talg und Hautschüppchen. Flüssige Peelings arbeiten mit Säuren, grobe mit kleinen Körnchen. Ein- bis zweimal pro Woche reicht, nie auf gereizter oder verletzter Kopfhaut."),
]

P = [
# ---------- Peelings ----------
("bpp","Balea Professional","Kopfhautpflege Peeling Tiefenreinigung","peeling","Peeling flüssig",
 "Klares AHA-Peeling: Glykolsäure steht an 2. Stelle, laut Etikett 4 %. Dazu etwas Panthenol.",
 "Glykolsäure, Panthenol","ohne Parfum, ohne Alkohol",
 "Auf die Kopfhaut geben, 15 bis 20 Minuten einwirken lassen und mit Shampoo auswaschen. Passt gut bei fettender Kopfhaut und Rückständen. Bei sensibler Kopfhaut erst an einer kleinen Stelle testen.",D),
("hsr","head&shoulders","Derma x Pro Scalp Reset Pre-Shampoo","peeling","Peeling flüssig",
 "Eigentlich eine milde Vorreinigung: ein Tensid, dazu Zitronensäure und Salicylsäure.",
 "Salicylsäure, Zitronensäure, mildes Tensid","mit Parfum und Menthol",
 "Nur auf die feuchte Kopfhaut, etwa 3 Minuten einmassieren, ausspülen und dann wie gewohnt waschen. Wegen Parfum und Menthol eher nichts für sensible Kopfhaut.",D),
("lps","L'Oréal Paris Elvital","Hydra Hyaluronic Pure Serum","peeling","Peeling flüssig",
 "Peeling-Serum mit Glykolsäure. Alkohol steht an 2. Stelle, die Salicylsäure und das Hyaluron aus dem Namen erst hinter dem Parfum.",
 "Glykolsäure, etwas Salicylsäure","mit Parfum, Alkohol an 2. Stelle, Pfefferminzöl",
 "Auf die trockene Kopfhaut, 15 Minuten einwirken lassen, dann waschen. Gedacht für fettige Kopfhaut. Bei trockener oder sensibler Kopfhaut eher nicht. Bei dm gerade nicht gelistet.",D),
("isp","ISANA Professional","Kopfhaut-Peeling Tiefenreinigung","peeling","Peeling flüssig",
 "Mildes Säurepeeling mit Milchsäure und Gluconolacton, dazu Glycerin und Panthenol.",
 "Milchsäure, Gluconolacton, Panthenol","ohne Parfum, ohne Alkohol",
 "Gluconolacton gehört zu den sanftesten Peeling-Säuren. Deshalb passt es auch, wenn deine Kopfhaut eher empfindlich ist.",D),
("ink","The INKEY List","Salicylic Acid Exfoliating Scalp Treatment","peeling","Peeling flüssig",
 "Salicylsäure steht an 3. Stelle, laut Marke 2 %. Dazu Betain und Panthenol.",
 "Salicylsäure 2 %, Betain, Panthenol","ohne Parfum, ohne Alkohol",
 "Vor der Haarwäsche auf die trockene Kopfhaut geben, kurz einwirken lassen und dann waschen. Salicylsäure löst Talg besonders gut. Passt deshalb vor allem bei fettender Kopfhaut und Schüppchen.",H),
("lpe","Living Proof","Scalp Care Exfoliator","peeling","Peeling flüssig",
 "Säurepeeling mit Mandelsäure, Glykolsäure und Gluconolacton.",
 "Mandelsäure, Glykolsäure, Gluconolacton","mit Parfum, ohne Alkohol",
 "Wird vor dem Shampoo verwendet. Mandelsäure und Gluconolacton gelten als eher sanfte Säuren.",H),
("mnp","Maria Nila","Purifying Cleanse Exfoliating Serum","peeling","Peeling flüssig",
 "Säurepeeling: Glykolsäure steht an 3. Stelle, dazu Salicyl-, Milch- und Apfelsäure, Aloe und Panthenol.",
 "Glykolsäure, Salicylsäure, Milchsäure, Panthenol","mit Parfum, ohne Alkohol",
 "Gedacht für fettige, juckende oder schuppige Kopfhaut. Vier Säuren auf einmal, deshalb nicht öfter als nötig verwenden.",H),
("ars","Aromatica","Rosemary Scalp Scrub","peeling","Peeling grob",
 "Grobes Peeling mit Meersalz, das gleichzeitig reinigt, weil Tenside enthalten sind.",
 "Meersalz, Rosmarin, Tenside","mit Menthol und ätherischen Ölen",
 "Auf die nasse Kopfhaut geben, sanft massieren, aufschäumen und ausspülen. Die Salzkörnchen lösen sich dabei auf. Nicht rubbeln, und nichts für sensible Kopfhaut.",H),
("mos","Moroccanoil","Purifying Pre-Wash Scalp Scrub","peeling","Peeling grob",
 "Grobes Peeling mit gemahlenen Arganschalen, dazu ein mildes Tensid und Öle.",
 "Arganschalen-Pulver, Arganöl","mit Parfum und Menthol",
 "Vor dem Shampoo auf die feuchte Kopfhaut, sanft einmassieren und ausspülen. Säuren sind nur in Spuren drin, die Arbeit machen die Körnchen.",H),
("nex","Nioxin","Scalp Purifying Exfoliator","peeling","Peeling grob",
 "Gel mit feinen Körnchen aus Cellulose, dazu etwas Sheabutter und Minzöl.",
 "Cellulose-Körnchen, Niacinamid, Panthenol","mit Parfum und Minzöl",
 "Auf die feuchte Kopfhaut vor dem Shampoo, sanft massieren und ausspülen. Die Körnchen sind fein, trotzdem nicht rubbeln.",H),

# ---------- Kopfhautpflegen Drogerie ----------
("bps","Balea Professional","Kopfhautpflege Serum Sensitive","normal trocken sensibel juckreiz","Serum",
 "Sehr milde Pflege mit 5 % Panthenol und Glycerin, dazu etwas Weißtee-Extrakt.",
 "Panthenol, Glycerin, Weißtee-Extrakt","ohne Parfum, ohne Alkohol",
 "Abends auf die betroffenen Stellen geben und am nächsten Morgen waschen. Das enthaltene Öl-Ersatzmittel kann den Ansatz etwas beschweren, deshalb lieber vor einer Wäsche nutzen.",D),
("nqt","NEQI","Haar-Tonic Forbidden Finish Rosemary","fettend","Tonikum · ohne Ausspülen",
 "Erfrischendes Tonic: Alkohol steht an 2. Stelle, dann Rosmarinöl, Koffein und Rizinusöl. Das Kupferpeptid aus der Werbung steht fast am Ende.",
 "Rosmarinöl, Koffein, Kupferpeptid","mit Duftstoffen, Alkohol an 2. Stelle, Kampfer",
 "Gehört auf die Kopfhaut. Bei dm steht in der Anwendung „Längen und Spitzen“, das ergibt für ein Kopfhaut-Tonic wenig Sinn. Es wird mit Rosmarin gegen Haarverlust in Verbindung gebracht. Gut belegt ist das bei Kosmetik nicht. Nichts für trockene oder sensible Kopfhaut.",D),
("bkt","Balea","Kopfhaut Tonikum beauty essentials","normal fettend","Tonikum · ohne Ausspülen",
 "Leichtes Tonikum mit Glycerin und Panthenol. Alkohol steht an 4. Stelle, dazu Pflanzenextrakte wie Rosmarin, Salbei und Ginkgo.",
 "Glycerin, Panthenol, Rosmarin, Ginkgo","mit Parfum, Alkohol an 4. Stelle",
 "Laut Balea kann es die Durchblutung anregen und so für ein Gefühl von dichterem Haar sorgen. Gemeint ist ein Gefühl, kein messbar dichteres Haar.",D),
("gsf","Schwarzkopf Gliss","Haarserum scalp balance feuchtigkeitsspendend","normal fettend","Serum · ohne Ausspülen",
 "Leichte Feuchtigkeitspflege mit Hyaluron, Panthenol und Bisabolol. Alkohol steht aber an 2. Stelle.",
 "Hyaluron, Panthenol, Bisabolol","mit Parfum, Alkohol an 2. Stelle",
 "Wird als Pflege für trockene Kopfhaut beworben. Mit so viel Alkohol passt es aus meiner Sicht besser zu normaler oder schnell fettender Kopfhaut.",D),
("hsl","head&shoulders","Leave-In Serum Derma x Pro","schuppen fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 1. Stelle, dann Niacinamid, Koffein und der Anti-Schuppen-Wirkstoff Piroctone Olamine.",
 "Piroctone Olamine, Niacinamid, Koffein, Panthenol","mit Parfum, Alkohol an 1. Stelle",
 "Wird als Feuchtigkeitspflege beworben. Durch Piroctone Olamine passt es aus meiner Sicht vor allem bei Schuppen. Bei trockener Kopfhaut würde ich wegen des vielen Alkohols eher etwas anderes nehmen.",D),
("dgl","Dejan Garz","Leave-In Sebum Spray The Sensitive","fettend sensibel","Spray · ohne Ausspülen",
 "Leichtes Spray gegen schnelles Nachfetten: 5 % Niacinamid, 2 % L-Carnitin und 1 % Zink-PCA, sonst kaum etwas.",
 "Niacinamid, L-Carnitin, Zink-PCA, Grüntee","ohne Parfum, ohne Alkohol",
 "Das ist das Produkt, das gezielt den Talg regulieren soll. Niacinamid und Zink sind dafür gute Kandidaten. Ohne Öl und ohne Parfum, deshalb passt es auch, wenn die fettige Kopfhaut zusätzlich empfindlich ist.",D),
("dgs","Dejan Garz","Haarserum The Sensitive Scalp","normal trocken sensibel juckreiz","Serum · ohne Ausspülen",
 "Sehr gute Rezeptur für trockene, gereizte Kopfhaut: 5 % Panthenol, 3 % Urea, Glycerin, Niacinamid, Allantoin, Hafer und Ceramide.",
 "Panthenol, Urea, Allantoin, Ceramide, Hafer","ohne Parfum, ohne Alkohol",
 "Urea bindet Feuchtigkeit und lindert Juckreiz, Ceramide stärken die Hautbarriere. Eine der stärksten Rezepturen hier für trockene Kopfhaut.",D),
("sts","Santé","Leave-In Haarserum Tonikum Simply Sensitive","normal trocken sensibel juckreiz fettend","Tonikum · ohne Ausspülen",
 "Milde, wässrige Pflege mit Glycerin, Panthenol und Betain, dazu Fermente und Alge.",
 "Glycerin, Panthenol, Betain, Milchsäure","ohne Parfum, ohne Alkohol",
 "Leicht und ohne Öl, deshalb passt es auch bei schnell fettender Kopfhaut, die Feuchtigkeit braucht. Das beworbene PDRN steht weit hinten.",D),
("bmt","Balea med","Kopfhaut Tonikum Ultra Sensitive Totes Meer","normal trocken sensibel juckreiz fettend","Tonikum · ohne Ausspülen",
 "Kurze, milde Liste: Glycerin, Panthenol, Meersalz, Allantoin und Niacinamid.",
 "Glycerin, Panthenol, Allantoin, Niacinamid","ohne Parfum, ohne Alkohol",
 "Sehr wenige Inhaltsstoffe, das ist bei empfindlicher Kopfhaut ein Vorteil. Leicht genug auch für schnell fettende Kopfhaut.",D),
("alk","alverde","Haarserum Kopfhaut Balance","normal trocken sensibel juckreiz","Serum",
 "Milde Pflege mit Aloe, Glycerin, Bisabolol, Ectoin und Hafer, dazu etwas Sonnenblumenöl.",
 "Aloe, Glycerin, Bisabolol, Ectoin, Hafer","ohne Parfum, ohne Alkohol",
 "Mindestens 15 Minuten einwirken lassen oder über Nacht, dann bei Bedarf auswaschen. Wegen des Öls lieber vor einer Wäsche nutzen.",D),
("gsk","Schwarzkopf Gliss","Haarserum scalp balance klärend","fettend","Serum · ohne Ausspülen",
 "Pflege für schnell fettende Kopfhaut: Alkohol steht an 2. Stelle, dazu Sarcosin, Niacinamid, Panthenol und Bisabolol.",
 "Sarcosin, Niacinamid, Panthenol, Bisabolol","mit Parfum, Alkohol an 2. Stelle",
 "Sarcosin und Niacinamid sollen den Talg regulieren. Der Alkohol sorgt für das frische Gefühl. Nichts für trockene oder sensible Kopfhaut.",D),
("hsd","head&shoulders","Kopfhaut Serum Derma x Pro Density Booster","schuppen fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 1. Stelle, dann Niacinamid, Koffein und Piroctone Olamine. Keratin, Biotin und Rosmarin stehen weit hinten.",
 "Piroctone Olamine, Niacinamid, Koffein","mit Parfum, Alkohol an 1. Stelle, Menthol",
 "Wird für mehr Haardichte beworben. Belegt ist bei Kosmetik vor allem, dass weniger Haare abbrechen und ausfallen, wenn die Kopfhaut gesund ist. Durch Piroctone Olamine passt es gut bei Schuppen.",D),
("lfb","L'Oréal Paris Elvital","Haarserum Fiber Booster Anti-Haarverlust","fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dann Niacinamid und Aminexil. Viele Duftstoffe stehen weit vorne.",
 "Aminexil, Niacinamid, Ingwer","mit vielen Duftstoffen, Alkohol an 2. Stelle",
 "Aminexil soll die Haarwurzel länger halten. Die Studien dazu kommen vor allem vom Hersteller. Wegen Alkohol und Duft nichts für sensible oder trockene Kopfhaut.",D),
("pga","Pantene Pro-V","Grow Abundant Anti-Haarverlust Kopfhautserum","schuppen fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 1. Stelle, dann Niacinamid und Piroctone Olamine, dazu Menthol.",
 "Niacinamid, Piroctone Olamine, Panthenol","mit Parfum, Alkohol an 1. Stelle, Menthol",
 "Gerade nicht bei dm, aber bei Rossmann. Wird gegen Haarverlust beworben. Durch Piroctone Olamine passt es aus meiner Sicht auch bei Schuppen.",D),
# ---------- Rossmann ----------
("ogx","OGX","ProGrowth + Peptide Scalp Serum","normal sensibel","Serum · ohne Ausspülen",
 "Leichtes Serum mit Panthenol, Erbsenpeptid, Niacinamid und Koffein.",
 "Erbsenpeptid, Niacinamid, Koffein, Panthenol","ohne Parfum, ohne Alkohol",
 "Wird für kräftigeres, dichteres Haar beworben. Der Name passt zu den Inhaltsstoffen, die Wirkung auf das Haarwachstum ist aber nicht gut belegt.",D),
("shv","Salt House Totes Meer","Anti-Haarverlust Kopfhaut-Fluid Aktiv","normal fettend","Fluid · ohne Ausspülen",
 "Glycerin, Alkohol an 3. Stelle, dann Panthenol, Koffein, Meersalz, Niacinamid und Urea. Dazu Menthol und Minzöl.",
 "Koffein, Panthenol, Niacinamid, Urea","mit Parfum, Alkohol an 3. Stelle, Menthol",
 "Auf der Packung steht „empfindliche und trockene Kopfhaut“. Mit Menthol, Minzöl und Parfum würde ich es dafür eher nicht nehmen.",D),
("shf","Salt House Totes Meer","Anti-Schuppen Kopfhaut-Fluid Forte","schuppen","Fluid · ohne Ausspülen",
 "Glycerin und Meersalz, Alkohol an 4. Stelle, dann Panthenol, Niacinamid, Teebaumöl und Piroctone Olamine.",
 "Piroctone Olamine, Teebaumöl, Zink, Panthenol","ohne Parfum, Alkohol an 4. Stelle, Minzöl",
 "Mit Piroctone Olamine ein echtes Anti-Schuppen-Fluid. Glycerin und Panthenol machen es milder als viele andere Anti-Schuppen-Produkte.",D),
("sha","Salt House Totes Meer","Anti-Juckreiz Kopfhaut-Fluid Akut","normal trocken sensibel juckreiz","Fluid · ohne Ausspülen",
 "Milde Feuchtigkeitspflege mit Glycerin, Panthenol, Allantoin, Niacinamid und Arginin. Alkohol steht weit hinten.",
 "Glycerin, Panthenol, Allantoin, Niacinamid","ohne Parfum, Alkohol weit hinten",
 "Urea steht anders als die Packung vermuten lässt fast am Ende. Die Arbeit machen Glycerin, Panthenol und Allantoin.",D),
("abc","Australian Bodycare","Scalp Serum Treatment Mask","schuppen","Kur",
 "Kur mit Glycerin, Emulgatoren und Teebaumöl an 6. Stelle, dazu Macadamiaöl.",
 "Teebaumöl, Glycerin, Allantoin","Teebaumöl und Menthol",
 "Teebaumöl kann gegen den Schuppen-Hefepilz helfen, ist aber schwächer belegt als Piroctone Olamine. Teebaumöl kann reizen, deshalb nicht bei sensibler Kopfhaut.",D),
("lsg","Lee Stafford","Grow Strong & Long Stimulating Scalp Serum","normal fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dann Glycerin, Zuckerrohr- und Fruchtextrakte, Panthenol und mehrere Proteine.",
 "Panthenol, Weizen- und Lupinenprotein, Kreatin","mit Parfum, Alkohol an 2. Stelle",
 "Wird gegen Haarbruch und für längeres Haar beworben. Proteine an der Kopfhaut stärken die Längen nicht. Gegen Haarbruch hilft Pflege in den Längen.",D),
("iss","ISANA Professional","Kopfhaut-Serum Sensitive Pflege","normal trocken sensibel juckreiz","Serum",
 "Sehr milde Pflege: Panthenol steht an 2. Stelle, dazu Glycerin, Allantoin, Bisabolol und Hyaluron.",
 "Panthenol, Glycerin, Allantoin, Bisabolol, Hyaluron","ohne Parfum, ohne Alkohol",
 "Enthält pflegende Öl-Ersatzstoffe. Bei schnell fettender Kopfhaut deshalb lieber vor einer Wäsche nutzen.",D),
("nst","NEQI x the.beautiful.people","Scalp Care Treatment Stylist Edition","normal","Spray",
 "Mildes Spray mit Glycerin, Fermenten, Bisabolol, Centella und Hafer. Enthält auch ein mildes Tensid.",
 "Glycerin, Bisabolol, Centella, Hafer","mit Parfum, ohne Alkohol",
 "Eine milde Allround-Pflege. Wegen des Parfums nicht meine erste Wahl bei sensibler Kopfhaut.",D),
("alt","Alterra","Kopfhaut-Elixier Bio-Hafer","normal trocken sensibel fettend","Spray · ohne Ausspülen",
 "Sehr kurze, milde Liste: Glycerin, Betain, Inulin, etwas Zink-PCA, Milchsäure und Hafer.",
 "Glycerin, Betain, Inulin, Zink-PCA, Hafer","ohne Parfum, ohne Alkohol",
 "Leicht und ohne Öl, deshalb passt es auch bei schnell fettender Kopfhaut. Das Zink steht allerdings weit hinten.",D),
# ---------- Öle ----------
("bmo","Balea med","Haaröl Ultra Sensitive 3in1","trocken sensibel normal","Öl · wird ausgewaschen",
 "Sonnenblumen- und Jojobaöl mit Panthenol-Abkömmling und Ceramid.",
 "Sonnenblumenöl, Jojobaöl, Ceramid","ohne Parfum",
 "Als Kopfhaut-Öl mindestens eine Stunde oder über Nacht einwirken lassen, dann auswaschen. Bei Schuppen eher nicht, denn Öle können dem Schuppen-Hefepilz Futter geben.",D),
("bcr","Bali Curls","Haar- & Kopfhautöl Rosmarin","trocken normal","Öl · wird ausgewaschen",
 "Ölmischung aus Soja-, Rizinus-, Sapote-, Kokos- und Jojobaöl mit Rosmarinöl, dazu Kampfer und Menthol.",
 "Rosmarinöl, Rizinusöl, Jojobaöl","Rosmarinöl, Kampfer und Menthol",
 "Für dünner werdendes Haar beworben. Für Rosmarinöl gegen Haarausfall gibt es nur wenige kleine Studien. Wegen Kampfer und Menthol nichts für sensible Kopfhaut, und bei Schuppen eher nicht.",D),
("dsj","Dr. Scheller","Jojobaöl","trocken sensibel normal","Öl · wird ausgewaschen",
 "100 % reines Bio-Jojobaöl, sonst nichts.",
 "Jojobaöl","ohne Duft",
 "Jojobaöl ist eigentlich ein flüssiges Wachs und ähnelt dem hauteigenen Fett. Als Kopfhaut-Öl vor der Wäsche gut verträglich. Bei Schuppen eher nicht.",D),
("dsa","Dr. Scheller","Arganöl","trocken normal","Öl · wird ausgewaschen",
 "100 % reines Bio-Arganöl, sonst nichts.",
 "Arganöl","ohne Duft",
 "Als Kopfhaut-Öl vor der Wäsche einmassieren und auswaschen. Bei Schuppen eher nicht, denn Öle können dem Schuppen-Hefepilz Futter geben.",D),

# ---------- High-End ----------
("euc","Eucerin","DermoCapillaire Urea Intensiv-Tonikum","normal trocken sensibel juckreiz","Tonikum · ohne Ausspülen",
 "Stark für trockene, juckende Kopfhaut: Urea steht an 2. Stelle, dazu Laktat, Polidocanol gegen Juckreiz und Licochalcone aus Süßholz.",
 "Urea, Laktat, Polidocanol, Licochalcone A","ohne Parfum, ohne Alkohol",
 "Laut Eucerin schon für Kinder ab 3 Jahren. Eine der überzeugendsten Rezepturen in diesem Guide für trockene und juckende Kopfhaut.",H),
("tom","The Ordinary","Multi-Peptide Serum for Hair Density","normal sensibel fettend","Serum · ohne Ausspülen",
 "Leichtes Serum mit Koffein, mehreren Peptiden und Pflanzenextrakten, ohne Öl.",
 "Koffein, Biotinoyl Tripeptide-1, Acetyl Tetrapeptide-3, Rotklee","ohne Parfum, ohne Alkohol",
 "Die Wirkstoffe gegen Haarverlust sind vor allem mit Studien der Rohstoff-Hersteller belegt. Mild genug für sensible Kopfhaut, leicht genug für fettende.",H),
("nbl","Niche Beauty Lab","Hair Density Scalp Treatment","normal","Spray · ohne Ausspülen",
 "Viele Wirkstoffe: Koffein, Peptide, Panthenol und Biotin, dazu Kurkuma- und Oliven-Zellkulturen.",
 "Koffein, Peptide, Panthenol, Biotin","ohne Parfum, Alkohol weit hinten",
 "Abends auf die Kopfhaut sprühen und drin lassen. Die Peptide sind dieselben wie bei The Ordinary. Den beworbenen Wirkstoff „Densidyl“ finde ich in der Liste nicht unter diesem Namen.",H),
("kgs","Kérastase","Genesis Sérum Anti-Chute Fortifiant","fettend schuppen","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dann Aminexil, Piroctone Olamine, Koffein und Niacinamid.",
 "Aminexil, Piroctone Olamine, Koffein, Niacinamid","mit Parfum, Alkohol an 2. Stelle",
 "Täglich, mindestens 6 Wochen. Wird gegen Haarausfall durch Haarbruch beworben. Durch Piroctone Olamine hilft es auch bei Schuppen.",H),
("ksy","Kérastase","Symbiose Sérum Cellulaire Nuit","schuppen","Serum · ohne Ausspülen",
 "Nachtserum gegen Schuppen: Alkohol steht an 2. Stelle, dazu Piroctone Olamine, Salicylsäure und Squalan.",
 "Piroctone Olamine, Salicylsäure, Squalan","mit Parfum, Alkohol an 2. Stelle",
 "Ein echtes Anti-Schuppen-Serum. Kérastase empfiehlt es auch für sensible Kopfhaut. Mit Alkohol und Parfum würde ich da vorsichtig sein.",H),
("nnd","Nioxin","Night Density Rescue Serum","fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 1. Stelle, dann Koffein und Panthenol, dazu Parfum und Menthol weit vorne.",
 "Koffein, Panthenol, Ingwer","mit Parfum, Alkohol an 1. Stelle, Menthol",
 "Wird für mehr Haardichte beworben. Viel Alkohol und Menthol, deshalb nichts für trockene oder sensible Kopfhaut.",H),
("lpd","Living Proof","Scalp Care Density Serum","normal fettend","Serum · ohne Ausspülen",
 "Leichtes Serum mit Glycerin, Süßholz, Ferment, Erbse und Zink, dazu Brennnessel und Grüntee.",
 "Glycerin, Süßholz, Zink, Brennnessel","mit Parfum, ohne Alkohol",
 "Ohne Alkohol und ohne Öl, deshalb gut für normale und schnell fettende Kopfhaut.",H),
("tos","The Ordinary","Natural Moisturizing Factors + HA for Scalp","normal trocken","Serum · ohne Ausspülen",
 "Feuchtigkeitspflege mit Squalan, Hyaluron, Aminosäuren, Urea und Zucker, also den Feuchthaltefaktoren der Haut.",
 "Squalan, Hyaluron, Aminosäuren, Urea","ohne Parfum, ohne Alkohol",
 "Enthält Hexylnicotinat, das kann kurz kribbeln oder die Haut rot machen. Bei sehr sensibler Kopfhaut deshalb erst an einer kleinen Stelle testen.",H),
("vab","Vichy","Dercos Aminexil Clinical R.E.G.E.N. Booster","fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dann Niacinamid und 1,5 % Aminexil, dazu Ingwer.",
 "Aminexil, Niacinamid, Ingwer","mit Parfum, Alkohol an 2. Stelle",
 "Auf der Flasche steht „für empfindliche Kopfhaut“. Mit Alkohol an 2. Stelle und Parfum sehe ich das anders.",H),
("vad","Vichy","Dercos Anti-Dandruff Serum","schuppen","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dazu Piroctone Olamine, Niacinamid, Centella und Hyaluron.",
 "Piroctone Olamine, Niacinamid, Centella, Hyaluron","mit Parfum, Alkohol an 2. Stelle",
 "Ein echtes Anti-Schuppen-Serum. Die „10 Schuppen-Symptome“ aus der Werbung sind Marketing, die Arbeit macht Piroctone Olamine.",H),
("rag","Redken","Acidic Grow Full Serum","normal fettend","Spray · ohne Ausspülen",
 "Leichtes Spray mit Glycerin, Koffein und Hyaluron, dazu Fermente und etwas Azelainsäure.",
 "Koffein, Hyaluron, Glycerin","mit Parfum, ohne Alkohol",
 "Ohne Alkohol und ohne Öl, deshalb gut für normale und schnell fettende Kopfhaut. Mehr Fülle verspricht vor allem das zugehörige System aus Shampoo und Conditioner.",H),
("kmp","Kérastase","Symbiose Micro-Peeling Cellulaire","peeling schuppen","Peeling grob",
 "Eher ein Peeling-Shampoo: Es reinigt mit zwei Sulfat-Tensiden, dazu 1,9 % Salicylsäure und gemahlene Argan- und Aprikosenkerne.",
 "Salicylsäure, Argan- und Aprikosenkern-Pulver, Squalan","mit Parfum und Menthol",
 "Laut Kérastase für sensible Kopfhaut mit Schuppen. Mit Sulfaten, Menthol und Parfum sehe ich das bei sensibler Kopfhaut kritisch. Gegen Schuppen hilft vor allem die Salicylsäure, sie löst die Schuppen. Einen Anti-Pilz-Wirkstoff hat es nicht.",H),
("kpo","Kérastase","Spécifique Potentialiste","normal fettend","Serum · ohne Ausspülen",
 "Alkohol steht an 2. Stelle, dann Bifidus-Ferment, ein Vitamin-C-Abkömmling und Präbiotika aus Zuckern.",
 "Bifidus-Ferment, Vitamin-C-Abkömmling, Präbiotika","mit Parfum, Alkohol an 2. Stelle",
 "Kérastase bewirbt es für alle Kopfhauttypen, auch für trockene und sensible. Mit Alkohol an 2. Stelle und Parfum würde ich es dort eher nicht nehmen. Die Wirkung auf das Mikrobiom der Kopfhaut ist bisher vor allem mit Studien des Herstellers belegt.",H),
]
