# Kopfhaut-Guide: Daten (Version 2, nach Lauras Korrekturen 06.10.2026)
# Felder: key, Marke, Produkt, Kategorien, Art, Einschätzung, wichtige Inhaltsstoffe, Duft/Alkohol, Anwendung (Kürzel oder eigener Text), Hinweis, Segment
D, H = "Drogerie", "High-End"
CATS = [
 ("normal", "Normale Kopfhaut", "Deine Kopfhaut macht keine Probleme, du möchtest sie einfach gut versorgen. Hier stehen Pflegen, die vor allem Feuchtigkeit geben, zum Beispiel mit Glycerin, Panthenol oder Hyaluron."),
 ("trocken", "Trockene / juckende Kopfhaut", "Die Kopfhaut spannt, juckt, fühlt sich rau an oder hat feine, trockene Schüppchen. Hier stehen Pflegen mit viel Feuchtigkeit und beruhigenden Wirkstoffen, zum Beispiel Urea, Panthenol, Glycerin, Allantoin oder Polidocanol, ohne viel Alkohol. Dazu Öle für vor der Wäsche. Juckt es trotz Pflege über Wochen, lass es beim Hautarzt anschauen."),
 ("sensibel", "Sensible Kopfhaut", "Die Kopfhaut reagiert schnell, wird rot oder brennt. Hier stehen nur milde Pflegen ohne Parfum und ohne viel Alkohol, meist mit beruhigenden Wirkstoffen wie Panthenol, Allantoin oder Bisabolol."),
 ("schuppen", "Schuppige Kopfhaut", "Gegen Schuppen, bei denen ein Hefepilz eine Rolle spielt. Wirklich dagegen arbeitet vor allem Piroctone Olamine. Hier stehen Pflegen, die so einen Wirkstoff enthalten. Am besten zusammen mit einem Anti-Schuppen-Shampoo."),
 ("fettend", "Schnell fettende Kopfhaut", "Der Ansatz ist schnell wieder fettig. Hier stehen leichte Pflegen ohne Öle: welche, die den Talg regulieren sollen, zum Beispiel mit Niacinamid oder Zink, und leichte Feuchtigkeitspflegen. Auch eine fettige Kopfhaut kann Feuchtigkeit brauchen."),
 ("haarausfall", "Bei Haarausfall", "Diese Produkte werden gegen Haarverlust beworben, meist mit Koffein, Aminexil, Rosmarin oder Peptiden. Sie pflegen die Kopfhaut, und eine gesunde Kopfhaut ist eine gute Grundlage für deine Haare. Dass Haare dadurch messbar dichter werden, ist bei Kosmetik aber kaum belegt, die Studien kommen meist von den Herstellern. Erblich bedingten Haarausfall halten sie nicht auf. Fallen dir über Wochen deutlich mehr Haare aus, lass das beim Hautarzt abklären. Sortiert nach Inhaltsstoffen: Oben stehen die Produkte mit den meisten und am weitesten vorne stehenden Wirkstoffen gegen Haarausfall, unten die schwächsten."),
 ("peeling", "Kopfhautpeeling", "Ein Peeling ist kein Pflegeprodukt für einen bestimmten Kopfhauttyp, sondern eine Reinigung zwischendurch. Es löst Rückstände, Talg und Hautschüppchen. Flüssige Peelings arbeiten mit Säuren, grobe mit kleinen Körnchen. Ein- bis zweimal pro Woche reicht, nie auf gereizter oder verletzter Kopfhaut."),
]

ANW = {
 "pflege": "Täglich mit der Scheiteltechnik auf die trockene Kopfhaut auftragen (so vermeidest du, dass deine Haare beschwert werden), ideal auch nach dem Waschen auf die feuchte Kopfhaut.",
 "peel_fl": "15 bis 20 Minuten vor der Haarwäsche mit dem Applikator auf die trockene Kopfhaut geben. Danach wie gewohnt waschen.",
 "peel_grob": "Auf die feuchte Kopfhaut geben und mit den Fingerspitzen einmassieren. Wenn das Auftragen schwierig ist: unter der Dusche einen Scheitel ziehen und das Produkt dort draufgeben. Danach wie gewohnt waschen.",
 "oel": "1 bis 2 Stunden vor der Haarwäsche auf die trockene Kopfhaut geben, einmassieren und gründlich auswaschen (nicht über Nacht drauflassen).",
}

P = [
# ---------- Peelings ----------
("bpp","Balea Professional","Kopfhautpflege Peeling Tiefenreinigung","peeling","Peeling flüssig",
 "Klares AHA-Peeling mit Glykolsäure, laut Etikett 4 %, dazu etwas Panthenol.",
 "Glykolsäure, Panthenol","ohne Parfum, ohne Alkohol","peel_fl","Nicht ideal für sehr sensible Kopfhaut.",D),
("hsr","head&shoulders","Derma x Pro Scalp Reset Pre-Shampoo","peeling","Peeling flüssig",
 "Milde Vorreinigung mit einem Tensid, Zitronensäure und Salicylsäure.",
 "Salicylsäure, Zitronensäure","mit Parfum und Menthol",
 "Auf die feuchte Kopfhaut vor dem Shampoo geben, etwa 3 Minuten einmassieren und dann wie gewohnt waschen.","Nicht ideal für sensible Kopfhaut.",D),
("lps","L'Oréal Paris Elvital","Hydra Hyaluronic Pure Serum","peeling","Peeling flüssig",
 "Peeling-Serum mit Glykolsäure für fettige Kopfhaut. Salicylsäure und Hyaluron sind nur in kleiner Menge drin.",
 "Glykolsäure, etwas Salicylsäure","mit Parfum und Alkohol","peel_fl","Nicht ideal für trockene oder sensible Kopfhaut. Bei dm gerade nicht gelistet.",D),
("isp","ISANA Professional","Kopfhaut-Peeling Tiefenreinigung","peeling","Peeling flüssig",
 "Sanftes Säurepeeling mit Milchsäure und Gluconolacton, dazu Glycerin und Panthenol.",
 "Milchsäure, Gluconolacton, Panthenol","ohne Parfum, ohne Alkohol","peel_fl","Durch die sanften Säuren auch für empfindliche Kopfhaut geeignet.",D),
("ink","The INKEY List","Salicylic Acid Exfoliating Scalp Treatment","peeling","Peeling flüssig",
 "Peeling mit 2 % Salicylsäure, die besonders gut Talg löst.",
 "Salicylsäure, Betain, Panthenol","ohne Parfum, ohne Alkohol","peel_fl","Ideal bei fettender Kopfhaut und Schüppchen.",H),
("lpe","Living Proof","Scalp Care Exfoliator","peeling","Peeling flüssig",
 "Säurepeeling mit eher sanften Säuren: Mandelsäure, Glykolsäure und Gluconolacton.",
 "Mandelsäure, Glykolsäure, Gluconolacton","mit Parfum, ohne Alkohol","peel_fl","",H),
("mnp","Maria Nila","Purifying Cleanse Exfoliating Serum","peeling","Peeling flüssig",
 "Säurepeeling mit Glykol-, Salicyl-, Milch- und Apfelsäure, dazu Aloe und Panthenol.",
 "Glykolsäure, Salicylsäure, Panthenol","mit Parfum, ohne Alkohol","peel_fl","Gedacht für fettige oder schuppige Kopfhaut. Nicht ideal für sensible Kopfhaut.",H),
("ars","Aromatica","Rosemary Scalp Scrub","peeling","Peeling grob",
 "Grobes Peeling mit Meersalz, das gleichzeitig reinigt.",
 "Meersalz, Rosmarin","mit Menthol und ätherischen Ölen","peel_grob","Nicht ideal für sensible Kopfhaut.",H),
("mos","Moroccanoil","Purifying Pre-Wash Scalp Scrub","peeling","Peeling grob",
 "Grobes Peeling mit gemahlenen Arganschalen und Arganöl.",
 "Arganschalen-Pulver, Arganöl","mit Parfum und Menthol","peel_grob","Nicht ideal für sensible Kopfhaut.",H),
("nex","Nioxin","Scalp Purifying Exfoliator","peeling","Peeling grob",
 "Gel mit feinen Körnchen aus Cellulose, dazu etwas Sheabutter.",
 "Cellulose-Körnchen, Niacinamid, Panthenol","mit Parfum und Minzöl","peel_grob","Nicht ideal für sensible Kopfhaut.",H),
("kmp","Kérastase","Symbiose Micro-Peeling Cellulaire","peeling schuppen","Peeling grob",
 "Peeling-Shampoo mit 1,9 % Salicylsäure und gemahlenen Kernen, es reinigt mit Sulfaten.",
 "Salicylsäure, Argan- und Aprikosenkern-Pulver","mit Parfum und Menthol","peel_grob","Löst Schuppen, hat aber keinen Anti-Pilz-Wirkstoff. Nicht ideal für sehr sensible Kopfhaut.",H),

# ---------- Kopfhautpflegen Drogerie ----------
("bps","Balea Professional","Kopfhautpflege Serum Sensitive","normal trocken sensibel","Serum",
 "Sehr milde Pflege mit 5 % Panthenol und Glycerin.",
 "Panthenol, Glycerin, Weißtee-Extrakt","ohne Parfum, ohne Alkohol",
 "pflege","",D),
("nqt","NEQI","Haar-Tonic Forbidden Finish Rosemary","fettend haarausfall","Tonikum",
 "Erfrischendes Tonic mit Rosmarinöl und Koffein.",
 "Rosmarinöl, Koffein, Kupferpeptid","mit Duftstoffen und Alkohol","pflege","Nicht ideal für sensible Kopfhaut und für trockene Kopfhaut als alleinige Pflege.",D),
("bkt","Balea","Kopfhaut Tonikum beauty essentials","normal fettend","Tonikum",
 "Leichtes Tonikum mit Glycerin, Panthenol und Pflanzenextrakten wie Rosmarin und Ginkgo.",
 "Glycerin, Panthenol, Rosmarin, Ginkgo","mit Parfum und Alkohol","pflege","",D),
("gsf","Schwarzkopf Gliss","Haarserum scalp balance feuchtigkeitsspendend","normal fettend","Serum",
 "Leichte Feuchtigkeitspflege mit Hyaluron und Panthenol.",
 "Hyaluron, Panthenol, Bisabolol","mit Parfum und Alkohol","pflege","Nicht ideal für trockene Kopfhaut als alleinige Pflege.",D),
("hsl","head&shoulders","Leave-In Serum Derma x Pro","schuppen fettend","Serum",
 "Mit dem Anti-Schuppen-Wirkstoff Piroctone Olamine und Niacinamid.",
 "Piroctone Olamine, Niacinamid, Koffein","mit Parfum und Alkohol","pflege","Nicht ideal für trockene Kopfhaut als alleinige Pflege.",D),
("dgl","Dejan Garz","Leave-In Sebum Spray The Sensitive","fettend sensibel","Spray",
 "Leichtes Spray gegen schnelles Nachfetten mit 5 % Niacinamid, 2 % L-Carnitin und 1 % Zink.",
 "Niacinamid, L-Carnitin, Zink-PCA","ohne Parfum, ohne Alkohol","pflege","Laut Dejan Garz bei Bedarf bis zu zweimal täglich, nicht ausspülen. Mild genug auch für empfindliche Kopfhaut.",D),
("dgs","Dejan Garz","Haarserum The Sensitive Scalp","normal trocken sensibel","Serum",
 "Eine der stärksten Rezepturen für trockene Kopfhaut: 5 % Panthenol, 3 % Urea, Allantoin, Hafer und Ceramide.",
 "Panthenol, Urea, Allantoin, Ceramide","ohne Parfum, ohne Alkohol","pflege","",D),
("sts","Santé","Leave-In Haarserum Tonikum Simply Sensitive","normal trocken sensibel fettend","Tonikum",
 "Milde, wässrige Pflege mit Glycerin, Panthenol und Betain.",
 "Glycerin, Panthenol, Betain","ohne Parfum, ohne Alkohol","pflege","",D),
("bmt","Balea med","Kopfhaut Tonikum Ultra Sensitive Totes Meer","normal trocken sensibel fettend","Tonikum",
 "Kurze, milde Liste mit Glycerin, Panthenol, Allantoin und Niacinamid.",
 "Glycerin, Panthenol, Allantoin, Niacinamid","ohne Parfum, ohne Alkohol","pflege","",D),
("alk","alverde","Haarserum Kopfhaut Balance","normal trocken sensibel","Serum",
 "Milde Pflege mit Aloe, Bisabolol, Ectoin und Hafer, dazu etwas Sonnenblumenöl.",
 "Aloe, Glycerin, Bisabolol, Ectoin","ohne Parfum, ohne Alkohol",
 "pflege","",D),
("gsk","Schwarzkopf Gliss","Haarserum scalp balance klärend","fettend","Serum",
 "Für schnell fettende Kopfhaut mit Sarcosin und Niacinamid.",
 "Sarcosin, Niacinamid, Panthenol","mit Parfum und Alkohol","pflege","Nicht ideal für sensible Kopfhaut und für trockene Kopfhaut als alleinige Pflege.",D),
("hsd","head&shoulders","Kopfhaut Serum Derma x Pro Density Booster","schuppen fettend haarausfall","Serum",
 "Mit Piroctone Olamine, Niacinamid und Koffein.",
 "Piroctone Olamine, Niacinamid, Koffein","mit Parfum, Alkohol und Menthol","pflege","Nicht ideal für trockene Kopfhaut als alleinige Pflege.",D),
("lfb","L'Oréal Paris Elvital","Haarserum Fiber Booster Anti-Haarverlust","fettend haarausfall","Serum",
 "Mit Aminexil und Niacinamid.",
 "Aminexil, Niacinamid, Ingwer","mit vielen Duftstoffen und Alkohol","pflege","Nicht ideal für sensible Kopfhaut und für trockene Kopfhaut als alleinige Pflege.",D),
("pga","Pantene Pro-V","Grow Abundant Anti-Haarverlust Kopfhautserum","schuppen fettend haarausfall","Serum",
 "Mit Niacinamid und Piroctone Olamine.",
 "Niacinamid, Piroctone Olamine, Panthenol","mit Parfum, Alkohol und Menthol","pflege","Gerade nicht bei dm, aber bei Rossmann.",D),
# ---------- Rossmann ----------
("ogx","OGX","ProGrowth + Peptide Scalp Serum","normal sensibel haarausfall","Serum",
 "Leichtes Serum mit Erbsenpeptid, Niacinamid, Koffein und Panthenol.",
 "Erbsenpeptid, Niacinamid, Koffein","ohne Parfum, ohne Alkohol","pflege","",D),
("shv","Salt House Totes Meer","Anti-Haarverlust Kopfhaut-Fluid Aktiv","normal fettend haarausfall","Fluid",
 "Mit Koffein, Panthenol, Niacinamid und Urea.",
 "Koffein, Panthenol, Niacinamid","mit Parfum, Alkohol und Menthol","pflege","Wegen Menthol nicht ideal für sensible Kopfhaut.",D),
("shf","Salt House Totes Meer","Anti-Schuppen Kopfhaut-Fluid Forte","schuppen","Fluid",
 "Anti-Schuppen-Fluid mit Piroctone Olamine und Teebaumöl, durch Glycerin und Panthenol eher mild.",
 "Piroctone Olamine, Teebaumöl, Panthenol","ohne Parfum, mit Alkohol","pflege","",D),
("sha","Salt House Totes Meer","Anti-Juckreiz Kopfhaut-Fluid Akut","normal trocken sensibel","Fluid",
 "Milde Feuchtigkeitspflege mit Glycerin, Panthenol und Allantoin.",
 "Glycerin, Panthenol, Allantoin, Niacinamid","ohne Parfum, wenig Alkohol","pflege","",D),
("abc","Australian Bodycare","Scalp Serum Treatment Mask","schuppen","Kur",
 "Kur mit Teebaumöl. Das kann gegen den Schuppen-Hefepilz helfen, ist aber schwächer belegt als Piroctone Olamine.",
 "Teebaumöl, Glycerin, Allantoin","Teebaumöl und Menthol",
 "Ein- bis zweimal pro Woche vor der Haarwäsche mit der Scheiteltechnik auf die trockene Kopfhaut geben, mindestens 30 Minuten bis eine Stunde einwirken lassen und dann auswaschen.","Nicht ideal für sensible Kopfhaut.",D),
("lsg","Lee Stafford","Grow Strong & Long Stimulating Scalp Serum","normal fettend","Serum",
 "Mit Panthenol, Proteinen und Fruchtextrakten.",
 "Panthenol, Weizen- und Lupinenprotein","mit Parfum und Alkohol","pflege","",D),
("iss","ISANA Professional","Kopfhaut-Serum Sensitive Pflege","normal trocken sensibel","Serum",
 "Sehr milde Pflege mit Panthenol, Glycerin, Allantoin, Bisabolol und Hyaluron.",
 "Panthenol, Allantoin, Bisabolol, Hyaluron","ohne Parfum, ohne Alkohol","pflege","",D),
("nst","NEQI x the.beautiful.people","Scalp Care Treatment Stylist Edition","normal","Spray",
 "Milde Allround-Pflege mit Glycerin, Bisabolol, Centella und Hafer.",
 "Glycerin, Bisabolol, Centella, Hafer","mit Parfum, ohne Alkohol","pflege","Mit Parfum, deshalb nicht erste Wahl bei sehr sensibler Kopfhaut.",D),
("alt","Alterra","Kopfhaut-Elixier Bio-Hafer","normal trocken sensibel fettend","Spray",
 "Sehr kurze, milde Liste mit Glycerin, Betain, Inulin, Zink und Hafer.",
 "Glycerin, Betain, Inulin, Hafer","ohne Parfum, ohne Alkohol","pflege","",D),
# ---------- Öle ----------
("bmo","Balea med","Haaröl Ultra Sensitive 3in1","trocken sensibel normal","Öl",
 "Sonnenblumen- und Jojobaöl mit Ceramid.",
 "Sonnenblumenöl, Jojobaöl, Ceramid","ohne Parfum","oel","Nicht ideal bei Schuppen, Öle können den Hefepilz füttern.",D),
("bcr","Bali Curls","Haar- & Kopfhautöl Rosmarin","trocken normal","Öl",
 "Ölmischung mit Rosmarinöl, dazu Kampfer und Menthol.",
 "Rosmarinöl, Rizinusöl, Jojobaöl","Rosmarinöl, Kampfer und Menthol","oel","Nicht ideal bei sensibler oder schuppiger Kopfhaut.",D),
("dsj","Dr. Scheller","Jojobaöl","trocken sensibel normal","Öl",
 "100 % reines Bio-Jojobaöl, es ähnelt dem hauteigenen Fett.",
 "Jojobaöl","ohne Duft","oel","Nicht ideal bei Schuppen.",D),
("dsa","Dr. Scheller","Arganöl","trocken normal","Öl",
 "100 % reines Bio-Arganöl.",
 "Arganöl","ohne Duft","oel","Nicht ideal bei Schuppen.",D),

# ---------- High-End ----------
("euc","Eucerin","DermoCapillaire Urea Intensiv-Tonikum","normal trocken sensibel","Tonikum",
 "Eine der besten Rezepturen hier für trockene, juckende Kopfhaut: Urea, Laktat, Polidocanol gegen Juckreiz und Licochalcone.",
 "Urea, Laktat, Polidocanol, Licochalcone A","ohne Parfum, ohne Alkohol","pflege","",H),
("tom","The Ordinary","Multi-Peptide Serum for Hair Density","normal sensibel fettend haarausfall","Serum",
 "Leichtes Serum mit Koffein, Peptiden und Pflanzenextrakten, ohne Öl.",
 "Koffein, Peptide, Rotklee","ohne Parfum, ohne Alkohol","pflege","",H),
("nbl","Niche Beauty Lab","Hair Density Scalp Treatment","normal haarausfall","Spray",
 "Mit Koffein, Peptiden, Panthenol und Biotin, dazu Kurkuma- und Oliven-Zellkulturen.",
 "Koffein, Peptide, Panthenol, Biotin","ohne Parfum, wenig Alkohol",
 "pflege","",H),
("kgs","Kérastase","Genesis Sérum Anti-Chute Fortifiant","fettend schuppen haarausfall","Serum",
 "Mit Aminexil, Piroctone Olamine, Koffein und Niacinamid.",
 "Aminexil, Piroctone Olamine, Koffein","mit Parfum und Alkohol","pflege","Nicht ideal für trockene Kopfhaut als alleinige Pflege.",H),
("ksy","Kérastase","Symbiose Sérum Cellulaire Nuit","schuppen","Serum",
 "Nachtserum mit Piroctone Olamine und Salicylsäure.",
 "Piroctone Olamine, Salicylsäure, Squalan","mit Parfum und Alkohol","pflege","Nicht ideal für sehr sensible Kopfhaut.",H),
("nnd","Nioxin","Night Density Rescue Serum","fettend haarausfall","Serum",
 "Mit Koffein und Panthenol.",
 "Koffein, Panthenol, Ingwer","mit Parfum, Alkohol und Menthol","pflege","Nicht ideal für sensible Kopfhaut und für trockene Kopfhaut als alleinige Pflege.",H),
("lpd","Living Proof","Scalp Care Density Serum","normal fettend haarausfall","Serum",
 "Leichtes Serum mit Glycerin, Süßholz, Zink und Brennnessel.",
 "Glycerin, Süßholz, Zink, Brennnessel","mit Parfum, ohne Alkohol","pflege","",H),
("tos","The Ordinary","Natural Moisturizing Factors + HA for Scalp","normal trocken","Serum",
 "Feuchtigkeitspflege mit Squalan, Hyaluron, Aminosäuren und Urea.",
 "Squalan, Hyaluron, Aminosäuren, Urea","ohne Parfum, ohne Alkohol","pflege","Kann kurz kribbeln. Bei sehr sensibler Kopfhaut erst an einer kleinen Stelle testen.",H),
("vab","Vichy","Dercos Aminexil Clinical R.E.G.E.N. Booster","fettend haarausfall","Serum",
 "Mit 1,5 % Aminexil, Niacinamid und Ingwer.",
 "Aminexil, Niacinamid, Ingwer","mit Parfum und Alkohol","pflege","Nicht ideal für sehr sensible Kopfhaut.",H),
("vad","Vichy","Dercos Anti-Dandruff Serum 10","schuppen","Serum",
 "Mit Piroctone Olamine, Niacinamid und Centella.",
 "Piroctone Olamine, Niacinamid, Centella","mit Parfum und Alkohol","pflege","Nicht ideal für sehr sensible Kopfhaut.",H),
("rag","Redken","Acidic Grow Full Serum","normal fettend haarausfall","Spray",
 "Leichtes Spray mit Koffein, Hyaluron und Glycerin.",
 "Koffein, Hyaluron, Glycerin","mit Parfum, ohne Alkohol","pflege","",H),
("kpo","Kérastase","Spécifique Potentialiste","normal fettend","Serum",
 "Mit Bifidus-Ferment, Vitamin-C-Abkömmling und Präbiotika.",
 "Bifidus-Ferment, Vitamin C, Präbiotika","mit Parfum und Alkohol","pflege","Nicht ideal für sensible Kopfhaut und für trockene Kopfhaut als alleinige Pflege.",H),
]

# Reihenfolge im Reiter „Bei Haarausfall“: stärkste Wirkstoffe oben
RANK_HAARAUSFALL = ["kgs","vab","lfb","tom","nbl","hsd","nnd","rag","shv","ogx","nqt","lpd","pga"]
